

server:
  port: 8080


spring:
  datasource:
    url: jdbc:oracle:thin:@47.104.176.200:1521:helowin
    username: root
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver



mybatis:
  type-aliases-package: com.example.accessingdatamysql.entity
  mapperLocations: classpath:mappers/*.xml
